version: '3'

services:
  skate-spot-api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - PASSWORD=${PASSWORD}
      - NAME=${NAME}
      - USER=${USER}  
      - GIN_MODE=release
    env_file:
      - .env

  db:
    image: "postgres:13-alpine"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_USER=${USER}
      - PGUSER=${USER}
      - POSTGRES_DB=${NAME}
    ports:
      - 5432:5432
  
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    
